import type { Metadata } from "next";
import "./globals.css";
import { Varela_Round } from 'next/font/google'
const varela = Varela_Round({
    subsets : ["latin"],
    weight : "400"
})
import {Providers} from "@/app/providers";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body className=" bg-slate-50">
          <Providers>
              <div className="bg-slate-50 fixed z-50  top-0 w-full h-[10vh] ">
                  <NavBar/>
              </div>
          <main className={`z-20 p-4 ${varela.className} mt-[9vh]`}>{children}</main>
              <div className=" w-full ">
                  <Footer/>
              </div>
          </Providers>
          </body>
      </html>
  );
}
