import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>
      <header className="p-4 shadow">
          <Link href="/">IndiaTour</Link>
          <form action="/search" method="get" className="inline-block ml-4">
              <input
                  name="q"
                  placeholder="Search places..."
                  className="border px-2"
              />
              <button type="submit">Search</button>
          </form>
      </header>
      <main className="p-4">{children}</main>
      </body>
      </html>
  );
}
